import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../src/styles/globals.css'; // Doğru import yolu
import Sidebar from '../components/Sidebar'; // Sidebar bileşenini import edin

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <Sidebar />
          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
